source "https://rubygems.org"

gem "jekyll-theme", :path => "../jekyll-theme"

gem 'jekyll', group: :jekyll_plugins

group :jekyll_plugins do
    gem 'jekyll-sitemap'
    gem 'jekyll-toc'
    gem 'jekyll-titles-from-headings'
   # gem 'jekyll-data'
end
